### ISSUE TITLE
打印页面调整修改

### ISSUE THREAD

**Issue by immo-leung** [Immortalshealth/TC1.0#4]
![default](https://user-images.githubusercontent.com/34183140/38006060-0a67d1ac-3276-11e8-9e0e-d45ca5903685.png)
![default](https://user-images.githubusercontent.com/34183140/38006064-0abc8634-3276-11e8-9e17-75d6de68b120.png)
系统由于之前的更新，新增部分内容后影响到打印页面，需要进行调整，把不必打印的字段和内容清除。主要包括病历模块中的病案记录和病程记录的打印页面。

**Comment by immo-fyh** [comment]
已处理。



yaohua.fan@immortalshealth.com
 
发件人： immo-leung
发送时间： 2018-03-28 10:55
收件人： Immortalshealth/TC1.0
抄送： 耀华; Assign
主题： [Immortalshealth/TC1.0] 打印页面调整修改 (#4)


系统由于之前的更新，新增部分内容后影响到打印页面，需要进行调整，把不必打印的字段和内容清除。主要包括病历模块中的病案记录和病程记录的打印页面。
